services:
  backend:
    build:
      context: ./library_api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./library_api:/code
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./library-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./library-frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  node_modules: